name: stwcs
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - astropy
  - numpy
  - matplotlib
  - stsci
  - stsci.sphinxext
  - pip:
    - sphinx_automodapi
    - git+https://github.com/spacetelescope/stsci_sphinx_theme.git#egg=stsci_sphinx_theme
